/**
 * Application configuration and feature flag types.
 * These types describe the configuration object injected by the server
 * into the CirculationAdmin constructor at startup.
 */

export type AdminRole =
  | "system"
  | "manager-all"
  | "manager"
  | "librarian-all"
  | "librarian";

export interface AdminRoleData {
  library?: string;
  role: AdminRole;
}

export interface DashboardCollectionsBarChart {
  width?: number;
}

export interface TestingFlags {
  [key: string]: boolean;
}

export interface FeatureFlags {
  enableAutoList?: boolean;
  reportsOnlyForSysadmins?: boolean;
  quicksightOnlyForSysadmins?: boolean;
  /** `showCircEventsDownload` controls whether the dashboard will have an
   option to download a CSV of circulation events. This should be false if
   circulation events are not available for download. */
  showCircEventsDownload?: boolean;
}

export interface Navigate {
  (collectionUrl: string, bookUrl: string, tab?: string): void;
}

export interface PathFor {
  (collectionUrl: string, bookUrl: string, tab?: string): string;
}

export interface ConfigurationSettings {
  /** A token generated by the server to prevent Cross-Site Request Forgery.
   The token should be included in an 'X-CSRF-Token' header in any non-GET
   requests. */
  csrfToken: string;

  /** DEPRECATED. Use the `showCircEventsDownload` feature flag instead.
   This can be removed once the backend stops sending it. */
  showCircEventsDownload: boolean;

  /** `settingUp` will be true if this is a new circulation manager and the
   admin interface has never been used before. The interface will show a page
   for configuring admin authentication. The admin will need to set that up
   and log in before accessing the rest of the interface. */
  settingUp: boolean;

  /** `email` will be the email address of the currently logged in admin. */
  email?: string;

  /** `roles` contains the logged in admin's roles and their associated
   libraries, where appropriate. */
  roles?: AdminRoleData[];

  tos_link_text?: string;
  tos_link_href?: string;

  /** Settings for a support contact link.
   * A URL for the application's support contact...
   * For example:
   * - mailto:helpdesk@example.com
   * - https://example.com/support
   */
  support_contact_url?: string; // Deprecated. Use `supportContactUrl`, instead.
  supportContactUrl?: string;
  // ... and a label for the support contact link.
  supportContactText?: string;

  featureFlags: FeatureFlags;

  /** `quickSightPagePath` contains the URL to the QuickSight dashboard page.
   Currently, this value does not change, so we can share it via fixed config. */
  quicksightPagePath: string;

  /** Configuration for dashboard collections barchart. */
  dashboardCollectionsBarChart?: DashboardCollectionsBarChart;
}
